# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Deprecated Panda dot com
tagline:          'A Blog about stuff'
description:      'Just a dude, who does stuff...'
url:              https;//deprecatedpanda.com
baseurl:          /

author:
  name:           'John Stauffacher'
  url:            https://twitter.com/g33kspeed

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

assets:

  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: true

